export const groups = [
  ['billing', 'duplicate-charge', 'train', [
    'My card statement has two completed charges for this month, but I only have one subscription. Please reverse the extra payment.',
    'Paid once. Charged twice. Can someone refund the second transaction?',
    'I retried checkout after a timeout. Both payments have now settled and I need one of them returned.',
    'We moved from monthly to annual billing yesterday. The annual payment is correct, but a second monthly payment was taken as well. Please credit that extra charge.',
    'There are two identical subscription debits dated Monday. Neither is marked pending by the bank. Could you investigate the duplicate?',
    'Our finance team matched the renewal invoice to two bank transactions. We need the excess payment reimbursed, not another account.',
    'The payment screen froze so I clicked again. I now see two settled debits. Please help me recover the duplicate amount.',
    'The plan is working fine. This ticket is just about the extra renewal charge on my card; please remove it.',
  ]],
  ['billing', 'refund-request', 'train', [
    'I purchased the yearly plan by mistake this morning. Can you refund it so I can choose monthly instead?',
    'We no longer need the unused seats we paid for yesterday. Is a refund possible under your policy?',
    'Please return the payment for my latest renewal. I have not used the service since it renewed.',
    'The trial converted to a paid subscription before I expected. I would like the charge reviewed for a refund.',
    'I understand the export issue is being investigated separately. My request here is reimbursement for the period we could not use the account.',
    'Can you confirm whether my refund was issued? The credit has not appeared on my statement yet.',
    'I bought the wrong subscription for our project. Before I purchase the right one, please explain the refund process for this order.',
    'Your colleague agreed to refund last week\'s charge. Could billing check its status and provide the refund reference?',
  ]],
  ['billing', 'subscription-cancellation', 'train', [
    'Please turn off automatic renewal at the end of our current paid term. We still need access until then.',
    'I want to cancel the subscription, not delete the data in my account. What do I need to do?',
    'Our project ends this month. Can you stop the next invoice and confirm the final access date?',
    'Could you move us back to the free plan when this billing period finishes?',
    'Cancel my paid membership please. I do not want another charge next month.',
    'We merged two workspaces and only need one subscription now. Please end the renewal on the old workspace.',
    'The app works well, but the budget has been cut. I need to arrange cancellation before the annual renewal.',
    'I can still sign in after cancelling. Can billing confirm that this is access for the remaining paid period and that no further payment is scheduled?',
  ]],
  ['billing', 'invoice-details', 'validation', [
    'The invoice lists our old legal entity. Please reissue it using the company details already saved in billing settings.',
    'Can you add our purchase order number to this month\'s invoice?',
    'We need a receipt showing the tax breakdown for the annual subscription payment.',
    'The latest invoice has the wrong billing address. How can I get a corrected copy for our accountant?',
    'Our tax registration was approved before renewal, but the invoice still includes the old tax treatment. Could your billing team review it?',
    'Please send a consolidated statement of the subscription payments we made this quarter.',
    'I am not reporting a download problem. The PDF opens correctly; the legal name printed on the invoice needs correcting.',
    'The invoice currency differs from the currency in our order confirmation. Please explain the billed amount before we approve payment.',
  ]],
  ['billing', 'payment-arrangement', 'test', [
    'The card used for renewal has expired. Where can I replace the payment method before the next invoice is due?',
    'Can our annual subscription be paid by bank transfer instead of card?',
    'The bank declined our renewal payment. Please help us settle the outstanding balance and restore paid access.',
    'We have a new company card. I need to update it for future subscription charges without changing the workspace owner.',
    'Our finance department needs payment terms before renewing. Who can confirm the due date and accepted payment methods?',
    'I received an overdue notice after sending the transfer. Can you reconcile the payment against our invoice?',
    'My card is valid but the payment was rejected. Could billing tell me how to retry the renewal safely?',
    'Please change the billing contact for payment reminders. The current recipient has left the company.',
  ]],
  ['technical', 'login-failure', 'train', [
    'The sign-in link opens a blank page. I requested a fresh one twice and both links fail in the same way.',
    'I can enter my password, but the login screen keeps sending me back to itself.',
    'Since this morning, signing in returns a server error before I reach the dashboard. My colleague sees it too.',
    'Password reset says it succeeded. The new password is still rejected when I try to log in.',
    'The verification code arrives immediately, but the form calls it expired even when I paste it straight away.',
    'Single sign-on worked yesterday. Today the redirect returns to an error page saying the session could not be created.',
    'After signing in on mobile, I am logged out as soon as I open a campaign. This happens in two browsers.',
    'My subscription is paid and active. I need help with the sign-in failure, not a billing change.',
  ]],
  ['technical', 'export-failure', 'train', [
    'Clicking Download CSV spins for a while and then reports an error. The results are visible on screen.',
    'The export finishes, but the downloaded file is empty even though this campaign has responses.',
    'JSON exports used to work for this project. Now the download returns a server error every time.',
    'The file contains only the header row. I selected all responses and the table shows forty entries.',
    'Some columns vanish from the CSV even though those fields have answers in the results view. Can you investigate?',
    'The export link created a minute ago says the file is missing. Generating a second export gives the same result.',
    'The download stops halfway through and leaves a file that will not open. A small campaign exports successfully.',
    'I am using the existing Excel export option. It produces a corrupted workbook instead of the file we received last week.',
  ]],
  ['technical', 'notification-failure', 'train', [
    'Response notifications are enabled, but no emails have arrived since Tuesday. New answers are appearing in the dashboard.',
    'Every new response now sends the same notification three times. It used to send only one.',
    'The notification link points to a page that says campaign not found, even though the campaign still exists.',
    'I switched off daily summaries, saved the setting and checked it again. The emails are still arriving.',
    'Our existing webhook delivery suddenly returns errors. The destination is reachable and the connection worked yesterday.',
    'The daily digest reports zero responses while the results page shows new submissions for that same day.',
    'Email alerts go to the previous recipient even after I save the replacement address and reload settings.',
    'The notification badge stays on after I read every item. Refreshing and signing back in do not clear it.',
  ]],
  ['technical', 'sync-failure', 'validation', [
    'The connected spreadsheet stopped receiving new rows overnight. The integration still says connected.',
    'Changes saved on my laptop never appear on my tablet, even after a refresh. Both devices use the same account.',
    'The sync job says complete, but only half of the records reached our destination.',
    'A record deleted in our source keeps reappearing after every sync. This did not happen before the latest update.',
    'The CRM integration that already exists is creating duplicate contacts on every run. Please investigate the repeated records.',
    'Refreshing the connection succeeds, but the sync immediately fails with a timeout. We have not changed the destination.',
    'Yesterday\'s edits are visible to me but not to other members. Everyone has reloaded the project and checked the same version.',
    'The synchronization status has been stuck on running for six hours with no new records transferred.',
  ]],
  ['technical', 'upload-failure', 'test', [
    'A valid PNG below the stated size limit is rejected when I try to upload our logo.',
    'The upload reaches one hundred percent, then the file disappears from the attachment list.',
    'I used your CSV template without changing the headers. Import still fails before it shows a preview.',
    'Dragging a file into the upload area does nothing. Choosing the same file with the browse button fails too.',
    'An image that uploaded successfully last week now gives an unsupported format error. It is the identical file.',
    'The import reports success but all dates are blank in the resulting records. The source file contains dates in the documented format.',
    'Replacing the logo shows the new image in the editor, but saving restores the old one. It happens on every attempt.',
    'Large uploads within the published limit stall near the end. Smaller files finish on the same connection.',
  ]],
  ['feature', 'new-integration', 'train', [
    'Could you add a direct integration with our issue tracker so each accepted response can create a ticket?',
    'There is no calendar connector in the current integration list. We would like one for scheduling follow-up interviews.',
    'I know CSV download works. What we need is a new automatic export into our warehouse every night.',
    'Please consider adding a chat notification destination alongside the email alerts you already support.',
    'We currently copy results into our CRM by hand because this CRM has no connector. Can you add one?',
    'Would you support a new automation trigger when a reviewer changes a label? The existing trigger only fires for new answers.',
    'Our team uses a different storage provider from the supported ones. Is a native connector for it something you could build?',
    'The current integration works as documented. I would like it extended to include review decisions as well as raw responses.',
  ]],
  ['feature', 'bulk-controls', 'train', [
    'Can you add a way to archive several campaigns at once? Opening each one individually takes a long time.',
    'I would like a select-all action for applying the same tag to many responses.',
    'The editor only lets me duplicate one question at a time. Please add duplication of a selected group.',
    'Could we edit the response deadline across multiple campaigns in a single operation?',
    'There is currently no bulk reviewer assignment. We need to allocate batches without opening each response.',
    'Please add a bulk rename tool for imported question titles, with a preview before applying changes.',
    'Individual deletions work. The missing capability is deleting a selected batch after one confirmation.',
    'We would like to copy the same introduction into several new drafts at once. This is not available in the current editor.',
  ]],
  ['feature', 'localization', 'train', [
    'Could contributors choose the language of the questionnaire from a selector? We currently have to create separate campaigns.',
    'Please add a right-to-left layout option for questionnaires written in Arabic.',
    'We would like translated button labels. The current fixed English labels make our Spanish campaign inconsistent.',
    'Could the date input support a configurable local format? At the moment only the default format is available.',
    'Please allow a different completion message for each language in the same campaign.',
    'We need a way to export translation keys for a translator and import the completed translations later.',
    'The current language settings work. I am requesting an additional locale that is not in the supported list.',
    'Would you add an owner-side preview for switching between language versions without changing the published campaign?',
  ]],
  ['feature', 'access-controls', 'validation', [
    'Please add a reviewer role that can label answers but cannot download the full dataset.',
    'Could we restrict a workspace member to one campaign? The current roles apply across the whole workspace.',
    'We need time-limited reviewer invitations. There is currently no option to make an invitation expire automatically.',
    'It would help to have an approval rule requiring two owners before a campaign is published.',
    'Can you build field-level visibility so reviewers do not see contact details when classifying answers?',
    'The existing owner permissions are working. We would like a new read-only reporting role for colleagues.',
    'Please add separate credentials for each automation with permissions limited to the exports it needs.',
    'Our policy requires a history of permission changes. Could you add an audit view for that?',
  ]],
  ['feature', 'reporting-capability', 'test', [
    'Could you add a chart comparing completion rates across multiple campaigns?',
    'The current results table is useful. I would also like a breakdown by question showing where people stop.',
    'Please add a saved report that compares this month\'s labels with last month\'s labels.',
    'We need confidence intervals on the summary charts. That option is not currently available.',
    'Could reports include agreement between reviewers when more than one person labels the same answer?',
    'Please let us schedule a weekly PDF summary. Manual exports work, but scheduled reports are missing.',
    'Would you add filters that let us compare new contributors with returning contributors in the same chart?',
    'I am requesting a new report for skipped questions. The existing answered-question report is behaving correctly.',
  ]],
  ['other', 'how-to', 'train', [
    'Where do I find the contributor link after publishing? I am setting up my first campaign.',
    'Could you explain the difference between an owner link and a reviewer link?',
    'Is there a guide to writing a useful classification rubric for a collection campaign?',
    'I have not tried the export yet. Which of the existing formats should I choose for opening answers in a spreadsheet?',
    'How do I preview a campaign before I approve it? Nothing is broken; I just cannot find the instructions.',
    'Could you point me to the documentation for pausing a live campaign?',
    'What does the validation split mean in the dataset manifest? I would appreciate an explanation of the terminology.',
    'How can I use the existing optional email field? I am looking for setup instructions rather than a new feature.',
  ]],
  ['other', 'privacy-request', 'train', [
    'Please explain how long contributor responses are retained after a campaign closes.',
    'I would like a copy of the personal information associated with my account.',
    'Can you direct our privacy team to your data processing agreement?',
    'Please remove my optional contact details from the response I submitted. I do not want to change the answer itself.',
    'Where are the servers that store campaign responses located?',
    'Who should we contact to discuss a data retention requirement before starting a research project?',
    'Our security review asks which service providers process account information. Where is the current list?',
    'I need to understand the procedure for a contributor withdrawing their data. Could you send the relevant policy?',
  ]],
  ['other', 'partnership', 'train', [
    'Our research group is interested in a joint workshop on collecting better labelled data. Who handles partnerships?',
    'Would someone from your team be available for an interview about the product for our newsletter?',
    'We run a community event for researchers and would like to discuss having you present a demonstration.',
    'I am writing a directory entry and want to confirm the company description before publishing it.',
    'Our university is exploring a collaboration on annotation practices. Can you connect us with the right person?',
    'Could we discuss a co-authored tutorial using public fictional data? This is an editorial enquiry, not a support issue.',
    'We would like permission to use a screenshot of your public website in a conference presentation.',
    'Who manages educational partnerships? We want to explore using the product in a methods course.',
  ]],
  ['other', 'employment-enquiry', 'validation', [
    'Are you currently hiring backend engineers? I could not find a careers page.',
    'Do you offer internships for students interested in developer tools?',
    'I would like to apply for a design role. Is there a suitable address for employment enquiries?',
    'Could you tell me whether your team accepts remote job applications?',
    'I am following up on an application I submitted last week. Who should I contact about the recruitment process?',
    'Does your company work with independent accessibility consultants? I am enquiring about contract opportunities.',
    'Is there an open position related to customer education? I would like to learn about the requirements.',
    'Your work on data collection interests me. Where do you post future vacancies?',
  ]],
  ['other', 'positive-feedback', 'test', [
    'Just a quick thank you. We finished our first collection round and the setup was straightforward.',
    'The support explanation yesterday solved my confusion. No further action is needed.',
    'I wanted to say that the question preview helped our team catch a mistake before publishing.',
    'We used the review view in class today and found it easy to explain. Thanks for making it clear.',
    'The export arrived correctly and our analyst has what they need. You can close the earlier ticket.',
    'Our volunteers liked answering one question at a time. Passing along their positive feedback.',
    'Everything is working after the instructions you sent. Thank you for the help.',
    'No request this time, just appreciation for the clear documentation on reviewing answers.',
  ]],
];

export const challenge = [
  ['Something is wrong with my account.', ['billing', 'technical', 'other'], 'Ask what happened and what outcome is needed.'],
  ['The invoice is wrong and the download button does not work. Can you sort both out?', ['billing', 'technical'], 'Separate the invoice correction from the broken download; no single primary request is stated.'],
  ['We cannot export in the format we need.', ['technical', 'feature', 'other'], 'Ask whether a supported export fails, a new format is wanted, or setup instructions are needed.'],
  ['I need help with notifications.', ['technical', 'feature', 'other'], 'Ask whether an existing alert fails, a new alert is wanted, or configuration help is needed.'],
  ['Please improve access for our reviewers.', ['technical', 'feature', 'other'], 'Ask whether access is failing, new permissions are requested, or role setup is unclear.'],
  ['Can we do something about the subscription?', ['billing', 'other'], 'Ask which subscription action or explanation the sender needs.'],
  ['We need translation support.', ['technical', 'feature', 'other'], 'Ask which existing or missing language capability is involved.'],
  ['The report is not what I expected.', ['technical', 'feature', 'other'], 'Ask what output was expected and whether it is a documented capability.'],
  ['I want a refund, and I also need you to add a reviewer-only role. Both are equally important.', ['billing', 'feature'], 'Split the explicitly equal requests into separate tickets.'],
  ['The project is finished. Close everything please.', ['billing', 'other'], 'Clarify whether to cancel payment, close a campaign, erase data, or all three.'],
  ['The payment is a problem. I also cannot sign in, and I do not know which one caused the other.', ['billing', 'technical'], 'Clarify the payment state and login error before assigning a single queue.'],
  ['It needs to work with our CRM.', ['technical', 'feature', 'other'], 'Ask whether a configured connector fails, a new connector is required, or setup help is needed.'],
];
